"""Export everything the web page needs to web/data.js (generated; run after changing the model or questions).

Usage: python3 scripts/build_web.py
"""
import json

import numpy as np

from scoring import K0, ROOT, Bank

bank = Bank()
P, explained = bank.pca2()
model = json.loads((ROOT / "data" / "model.json").read_text())


def r(a, n=6):
    return np.round(np.asarray(a, dtype=float), n).tolist()


data = {
    "k0": K0,
    "dimensions": [{k: d[k] for k in ("id", "name", "low", "high")} for d in model["dimensions"]],
    "tags": [{"id": t["id"], "name": t["name"], "category": t["category"], "description": t["description"],
              "v": r(bank.T[i])} for i, t in enumerate(bank.tags)],
    "questions": [{"id": q["id"], "text": q["text"], "w": r(bank.W[i]), "baseline": q["baseline"]}
                  for i, q in enumerate(bank.questions)],
    "pca": {"P": r(P), "explained": r(explained)},
    "range": {"lo": r(bank.lo), "hi": r(bank.hi)},
    "i18n": {},
}

# Translations: data/i18n/<lang>.json must cover exactly the same ids as the English source.
want = {"questions": {q["id"] for q in data["questions"]}, "dimensions": {d["id"] for d in data["dimensions"]},
        "tags": {t["id"] for t in data["tags"]}}
for path in sorted((ROOT / "data" / "i18n").glob("*.json")):
    tr = json.loads(path.read_text())
    for kind, ids in want.items():
        missing, extra = ids - set(tr[kind]), set(tr[kind]) - ids
        assert not missing and not extra, f"{path.name} {kind}: missing {sorted(missing)}, extra {sorted(extra)}"
    for d in tr["dimensions"].values():
        assert set(d) == {"name", "low", "high"}
    for t in tr["tags"].values():
        assert set(t) == {"name", "description"}
    data["i18n"][path.stem] = tr
out = ROOT / "web" / "data.js"
out.parent.mkdir(exist_ok=True)
out.write_text("// Generated by scripts/build_web.py. Do not edit.\nconst DATA = " + json.dumps(data, separators=(",", ":")) + ";\n"
               "if (typeof module !== 'undefined') module.exports = DATA;\n")
print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size / 1024:.0f} KB)")
